on:
  release:
    types:
      - created
jobs:
  release:
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login hub.docker.com -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make publish
